name: Build and Push Multi-Arch Docker Image + SBOM

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: docker.cloudsmith.io/${{ secrets.CLOUDSMITH_ORG }}/${{ secrets.CLOUDSMITH_REPO }}/hello-multiarch
  TAG: gh-actions

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Needed for Cosign OIDC signing

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Cloudsmith Docker registry
        uses: docker/login-action@v3
        with:
          registry: docker.cloudsmith.io
          username: ${{ secrets.CLOUDSMITH_USER }}
          password: ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
          provenance: true
          sbom: true

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Generate and upload SBOM attestation (Cosign)
        run: |
          cosign attest --predicate sbom.spdx.json --type spdx \
            $IMAGE_NAME:$TAG
        env:
          COSIGN_EXPERIMENTAL: "1"
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          TAG: ${{ env.TAG }}
